name: K6 Load Test
on: [push]

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install K6
        run: sudo apt-get install -y k6

      - name: Run K6 Load Test
        run: k6 run test-api.js
