name: K6 Load Test
on: [push]

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install K6
        run: |
          curl -s https://packagecloud.io/install/repositories/loadimpact/k6/script.deb.sh | sudo bash
          sudo apt install k6

      - name: Run K6 Test
        run: k6 run tests/test.js
        
      - name: Run K6 Test and Save Output
        run: k6 run --out json=results.json tests/test.js

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: results.json
